name: Node CI

on:
  push:
    branches:
      - master

jobs:
  Lint-and-test:
    runs-on: ubuntu-latest
    name: unit test
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm test 
          npm run lint
          npm run test:e2e
        env:
          CI: true
          apikey: ${{secrets.API_KEY}}
          url: ${{secrets.URL}}
